<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>de.crafttogether</groupId>
    <artifactId>CTCommons</artifactId>
    <version>1.1.3-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>CTCommons</name>
    <description>Library to centralize main functions for multiple plugins which will allow better maintaining capabilities and will lower general plugin sizes.</description>
    <url>https://github.com/CraftTogetherMC</url>

    <properties>
        <java.version>25</java.version>
        <spigot.version>26.2-R0.1-SNAPSHOT</spigot.version>
        <bungeecord.version>1.21-R0.4-SNAPSHOT</bungeecord.version>
        <velocity.version>4.1.0-SNAPSHOT</velocity.version>
        <cloud.annotations.version>2.1.0</cloud.annotations.version>
        <cloud.paper.version>2.0.0</cloud.paper.version>
        <cloud.bungee.version>2.0.0</cloud.bungee.version>
        <cloud.velocity.version>2.0.0</cloud.velocity.version>
        <cloud.extras.version>2.0.0</cloud.extras.version>
        <cloud.brigadier.version>2.0.0</cloud.brigadier.version>
        <log4j.version>2.26.1</log4j.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.build.number>NO-CI</project.build.number>
    </properties>

    <profiles>
        <profile>
            <id>ci</id>
            <activation>
                <property>
                    <name>env.BUILD_NUMBER</name>
                </property>
            </activation>
            <properties>
                <project.build.number>${env.BUILD_NUMBER}</project.build.number>
            </properties>
        </profile>
    </profiles>

    <repositories>

        <repository>
            <id>central</id>
            <url>https://repo.maven.apache.org/maven2/</url>
        </repository>

        <repository>
            <id>spigot-repo</id>
            <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
        </repository>

        <repository>
            <id>bungeecord-repo</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </repository>

        <repository>
            <id>paper-repo</id>
            <url>https://repo.papermc.io/repository/maven-public/</url>
        </repository>

        <repository>
            <id>MG-Dev Jenkins CI Maven Repository</id>
            <url>https://ci.mg-dev.eu/plugin/repository/everything</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>${spigot.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>net.md-5</groupId>
            <artifactId>bungeecord-api</artifactId>
            <version>${bungeecord.version}</version>
            <scope>provided</scope>

            <exclusions>
                <exclusion>
                    <groupId>io.netty</groupId>
                    <artifactId>netty-codec-compression</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.velocitypowered</groupId>
            <artifactId>velocity-api</artifactId>
            <version>${velocity.version}</version>
            <scope>provided</scope>
        </dependency>

        <!-- Platform-abstraction-layer -->
        <dependency>
            <groupId>de.crafttogether</groupId>
            <artifactId>platform-abstraction-layer-api</artifactId>
            <version>5.0.1</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>de.crafttogether</groupId>
            <artifactId>platform-abstraction-layer-bukkit</artifactId>
            <version>5.0.0</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>de.crafttogether</groupId>
            <artifactId>platform-abstraction-layer-bungeecord</artifactId>
            <version>5.0.0</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>de.crafttogether</groupId>
            <artifactId>platform-abstraction-layer-velocity</artifactId>
            <version>5.0.0</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.incendo</groupId>
            <artifactId>cloud-annotations</artifactId>
            <version>${cloud.annotations.version}</version>
            <scope>compile</scope>
        </dependency>

    <!-- Paper adapter -->
        <dependency>
            <groupId>org.incendo</groupId>
            <artifactId>cloud-paper</artifactId>
            <version>${cloud.paper.version}</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.incendo</groupId>
            <artifactId>cloud-bukkit</artifactId>
            <version>${cloud.paper.version}</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.incendo</groupId>
            <artifactId>cloud-bungee</artifactId>
            <version>${cloud.bungee.version}</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.incendo</groupId>
            <artifactId>cloud-velocity</artifactId>
            <version>${cloud.velocity.version}</version>
            <scope>compile</scope>
        </dependency>

        <!-- Optional: Brigadier + Extras -->
        <dependency>
            <groupId>org.incendo</groupId>
            <artifactId>cloud-brigadier</artifactId>
            <version>${cloud.brigadier.version}</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.incendo</groupId>
            <artifactId>cloud-minecraft-extras</artifactId>
            <version>${cloud.extras.version}</version>
            <scope>compile</scope>
        </dependency>

        <!-- Adventure -->
        <dependency>
            <groupId>net.kyori</groupId>
            <artifactId>adventure-api</artifactId>
            <version>5.2.0</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>net.kyori</groupId>
            <artifactId>adventure-platform-bukkit</artifactId>
            <version>4.4.1</version>
            <scope>compile</scope>
            <exclusions>
                <exclusion>
                    <groupId>net.kyori</groupId>
                    <artifactId>adventure-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>net.kyori</groupId>
            <artifactId>adventure-platform-bungeecord</artifactId>
            <version>4.4.1</version>
            <scope>compile</scope>
            <exclusions>
                <exclusion>
                    <groupId>net.kyori</groupId>
                    <artifactId>adventure-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>net.kyori</groupId>
            <artifactId>adventure-text-minimessage</artifactId>
            <version>5.2.0</version>
            <scope>compile</scope>
            <exclusions>
                <exclusion>
                    <groupId>net.kyori</groupId>
                    <artifactId>adventure-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>net.kyori</groupId>
            <artifactId>adventure-text-serializer-legacy</artifactId>
            <version>5.2.0</version>
            <scope>compile</scope>
            <exclusions>
                <exclusion>
                    <groupId>net.kyori</groupId>
                    <artifactId>adventure-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>net.kyori</groupId>
            <artifactId>adventure-text-serializer-plain</artifactId>
            <version>5.2.0</version>
            <scope>compile</scope>
            <exclusions>
                <exclusion>
                    <groupId>net.kyori</groupId>
                    <artifactId>adventure-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>net.kyori</groupId>
            <artifactId>adventure-text-serializer-gson</artifactId>
            <version>5.2.0</version>
            <scope>compile</scope>
            <exclusions>
                <exclusion>
                    <groupId>net.kyori</groupId>
                    <artifactId>adventure-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <!-- B-Stats -->
        <dependency>
            <groupId>org.bstats</groupId>
            <artifactId>bstats-bukkit</artifactId>
            <version>3.2.1</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.bstats</groupId>
            <artifactId>bstats-bungeecord</artifactId>
            <version>3.2.1</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.bstats</groupId>
            <artifactId>bstats-velocity</artifactId>
            <version>3.2.1</version>
            <scope>compile</scope>
        </dependency>

        <!-- MySQL -->
        <dependency>
            <groupId>com.zaxxer</groupId>
            <artifactId>HikariCP</artifactId>
            <version>7.1.0</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.mariadb.jdbc</groupId>
            <artifactId>mariadb-java-client</artifactId>
            <version>3.5.10</version>
            <scope>compile</scope>
            <exclusions>
                <exclusion>
                    <groupId>com.github.waffle</groupId>
                    <artifactId>waffle-jna</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <!-- Other -->
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>${log4j.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>${log4j.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.20.0</version>
        </dependency>

        <dependency>
            <groupId>org.jetbrains</groupId>
            <artifactId>annotations</artifactId>
            <version>26.1.0</version>
        </dependency>

        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>2.22.0</version>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.14.1</version>
                <configuration>
                    <release>${java.version}</release>

                    <annotationProcessorPaths>
                        <path>
                            <groupId>com.velocitypowered</groupId>
                            <artifactId>velocity-api</artifactId>
                            <version>${velocity.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>3.6.3</version>
                <configuration>
                    <failOnError>false</failOnError>
                    <doclint>none</doclint>
                    <quiet>true</quiet>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.6.2</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <createDependencyReducedPom>false</createDependencyReducedPom>
                    <relocations>
                        <relocation>
                            <pattern>org.incendo</pattern>
                            <shadedPattern>de.crafttogether.common.shaded.org.incendo</shadedPattern> <!-- Replace this -->
                        </relocation>
                        <relocation>
                            <pattern>io.leangen.geantyref</pattern>
                            <shadedPattern>de.crafttogether.common.shaded.typetoken</shadedPattern> <!-- Replace this -->
                        </relocation>
                        <relocation>
                            <pattern>de.exlll</pattern>
                            <shadedPattern>de.crafttogether.common.shaded.de.exlll</shadedPattern>
                        </relocation>
                        <relocation>
                            <pattern>org.bstats</pattern>
                            <shadedPattern>de.crafttogether.common.shaded.org.bstats</shadedPattern>
                        </relocation>
                        <relocation>
                            <pattern>org.mariadb.jdbc</pattern>
                            <shadedPattern>de.crafttogether.common.shaded.org.mariadb.jdbc</shadedPattern>
                        </relocation>
                        <relocation>
                            <pattern>org.yaml</pattern>
                            <shadedPattern>de.crafttogether.common.shaded.org.yaml</shadedPattern>
                        </relocation>
                    </relocations>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>3.1.0</version>
                <executions>
                    <execution>
                        <id>version-less-jar</id>
                        <phase>package</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <target>
                                <copy file="target/${project.name}-${project.version}.jar" tofile="target/static/${project.name}.jar"/>
                                <copy file="target/${project.name}-${project.version}.jar" tofile="target/static/${project.name}-${project.version}-${project.build.number}.jar"/>
                            </target>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>

        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>
</project>
