Settings:
  Language: en_EN
  Debug: false
Updates:
  DisableNotifications: false
  CheckForDevBuilds: true
  Notify:
    Console: true
    InGame: true
Messaging:
  Enabled: true
  Server:
    Port: 5000
    BindAddress: 127.0.0.1
    AcceptRemoteConnections: false
    PublicAddress: 127.0.0.1
    SecretKey: iliketrains