Settings:
  Language: en_EN
  Debug: false
Updates:
  DisableNotifications: false
  CheckForDevBuilds: true
  Notify:
    Console: true
    InGame: true
Messaging:
  Enabled: true
  Connection:
    Host: 127.0.0.1
    Port: 5000
    SecretKey: iliketrains