name: CTCommonsBukkit
version: 1.0-BETA3
build: NO-CI
description: Library to centralize main functions for multiple plugins which will allow better maintaining capabilities and will lower general plugin sizes.
authors: [ J0schlZ ]
website: https://github.com/CraftTogetherMC
main: de.crafttogether.ctcommons.CTCommonsBukkit
api-version: 1.17
commands:
  ctcommons:
    description: Shows the current version of the plugin and informations about updates
    usage: /ctcommons
    permission: ctcommons.command